plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\Kegiatan Kampus\\41. Web Animathics Studio\\AniMathics Lab\\experiments"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]